version: '3'

services:
  selenium-app:
    container_name: selenium-app
    build: .
    shm_size: 2gb
    ports:
      - "4444:4444"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
